# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 17:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TeamDefault', max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos', verbose_name='Логотип')),
                ('is_verified', models.BooleanField(default=False, help_text='Допущена ли к регестрации', verbose_name='Проверена')),
                ('wins', models.IntegerField(default=0)),
                ('looses', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('captain_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_captain', to=settings.AUTH_USER_MODEL, verbose_name='Капитан команды')),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
    ]
