# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_teamplayer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teamplayer',
            name='user',
        ),
        migrations.DeleteModel(
            name='TeamPlayer',
        ),
    ]
