# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-06 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20160525_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamplayer',
            name='role',
        ),
        migrations.AlterField(
            model_name='teamplayer',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Вступил в команду'), (3, 'Вышел из команды'), (1, 'Приглашен в команду')], verbose_name='Действие'),
        ),
    ]
