# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 09:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mixes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TeamDefault', max_length=120, unique=True)),
                ('type', models.CharField(default='CyberSport', max_length=120)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Миксы',
                'verbose_name': 'Микс',
            },
        ),
        migrations.CreateModel(
            name='MixPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mixes.Mixes', verbose_name='Микс')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Игрок')),
            ],
            options={
                'verbose_name_plural': 'Игроки',
                'verbose_name': 'Игрок',
            },
        ),
    ]
