# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mixes', '0002_mixes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='mixes',
            name='place',
            field=models.CharField(default='Club', max_length=120),
        ),
        migrations.AlterField(
            model_name='mixes',
            name='title',
            field=models.CharField(default='MixDefault', max_length=120, unique=True),
        ),
    ]
