# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-21 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160521_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Админ сайта, доступ в админку', verbose_name='Админ'),
        ),
    ]
