# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160522_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='nameless', max_length=20, verbose_name='Никнейм'),
        ),
    ]
