# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-25 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_inteam',
            field=models.BooleanField(default=False, help_text='Состоит ли в команде', verbose_name='В команде'),
        ),
    ]
