# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-13 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0005_auto_20160606_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_banned', models.BooleanField(default=False, help_text='Бан на конкретном турнире', verbose_name='Бан на турнире')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Teams', verbose_name='Команда')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='MixDefault', max_length=120, unique=True)),
                ('type', models.CharField(default='CyberSport', max_length=120)),
                ('data', models.DateField(default='2000-01-01')),
                ('place', models.CharField(default='Club', max_length=120)),
                ('is_online', models.BooleanField(default=False, help_text='Онлайн или лан', verbose_name='Тип турнира')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Турнир',
                'ordering': ['-timestamp'],
                'verbose_name_plural': 'Турниры',
            },
        ),
        migrations.AddField(
            model_name='tourplayer',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.Tours', verbose_name='Турнир'),
        ),
    ]
